#!/bin/bash -e

set -x
LOGF=/var/log/$(basename $0).log
exec 1> >(tee $LOGF)
exec 2>&1

echo "Chipsee Init beggin"
if [ -f /lib/udev/rules.d/80-net-setup-link.rules ]; then
	ln -sf /dev/null /lib/udev/rules.d/80-net-setup-link.rules
fi

COMPATIBLE=$(cat /proc/device-tree/compatible)
if [[ $COMPATIBLE =~ "stm32mp257f-eisd-1024600" ]]; then
    BOARDNAME="CS10600-STMP25-070"
elif [[ $COMPATIBLE =~ "stm32mp257f-eisd-1280720" ]]; then
    BOARDNAME="CS12720-STMP25-050"
else
    BOARDNAME="CS12800-STMP25-101"
fi

# backlight
if [[ "$BOARDNAME" == "CS12800-STMP25-101" ]]; then
    ln -sf /sys/class/backlight/panel-lvds-backlight/max_brightness /dev/max_brightness
    ln -sf /sys/class/backlight/panel-lvds-backlight/brightness /dev/brightness
    # LTE 4G Reset IO[PB15]
    gpioset -z PB15=0
    killall gpioset
    sleep 1
    gpioset -z PB15=1
else
    ln -sf /sys/class/backlight/panel-dsi-backlight/max_brightness /dev/max_brightness
    ln -sf /sys/class/backlight/panel-dsi-backlight/brightness /dev/brightness
    # LTE 4G Reset IO[PJ8]
    gpioset -z PJ8=0
    killall gpioset
    sleep 1
    gpioset -z PJ8=1
fi

if [ `systemctl is-enabled st-m33firmware-load` = "enabled" ]; then
    systemctl stop st-m33firmware-load.service
    systemctl disable st-m33firmware-load.service
fi

## Init Audio
/usr/bin/hpdet

# Init Bluetooth
/usr/bin/btinit &

echo "Chipsee Init end"
