#!/bin/bash -e

if [ `systemctl is-enabled st-m33firmware-load` = "enabled" ]; then
	systemctl stop st-m33firmware-load.service
	systemctl disable st-m33firmware-load.service
fi

## Init Audio
/usr/bin/hpdet

# Init Bluetooth
/usr/bin/btinit &

# LTE 4G Reset IO[PB15]
#gpioset -z PB15=0
#killall gpioset
#sleep 1
#gpioset -z PB15=1
